### ISSUE TITLE
stm32 support

### ISSUE THREAD

**Issue by clear-sky** [LuisMiCa/IRsmallDecoder#2]
hi 
i have a maple board besed on stm32f103ret6
i connected ir sensor output to pin a0
but can not recieve anything in nec or rc5 remote
my arduino cor is based on https://github.com/stm32duino/Arduino_Core_STM32

**Comment by LuisMiCa** [comment]
Hello,

As far as I'm concerned, you are the first one to try this library on a stm32 microcontroller, so I can't tell you that it worked before, on one of those microcontrollers.

So, let's start with a simple test to see if the interruptions are working:
- In your .ino file (or one of the examples) add the following line at the top:  
```#define IRSMALLD_DEBUG_STATE```
- Upload the sketch and start the Serial Monitor;
- Whenever you push a key on the remote (any remote, actually) you should see strings of numbers appearing. Mostly 0's if it's the wrong protocol.

Let me know if you get something or not. Then we will go from there.

**Comment by clear-sky** [comment]
hi dear luis
i added that define but in serial monitor can not see any code in both nec and rc5 remote
this is the output of my serial monitor
23:28:37.268 -> Waiting for a NEC remote control IR signal...
23:28:37.268 -> held 	addr 	cmd

**Comment by LuisMiCa** [comment]
I've read that the operating voltage of the stm32f103 is 3.3V.
Is the operating voltage of the IR sensor also 3.3V?

**Comment by clear-sky** [comment]
yes my ir sensor is hs0038a2
 i found two datasheet for this sensor
my refrence was page 1 of http://wiki.iranmicro.ir/wp-content/uploads/2013/10/HS0038A2.pdf
but page 2 of this datasheet says another thing https://html.alldatasheet.com/html-pdf/215919/VISHAY/HS0038A2/440/2/HS0038A2.html
i have another sensor vs838 will test it soon

**Comment by LuisMiCa** [comment]
Yes, that datasheet is not very clear about the supply voltage. But there's a small note that says: "tolerated supply voltage range : 4.5V<VS<5.5V".

I'm not sure about the board you have, but some STM32 have 5V tolerant pins:
<https://circuitdigest.com/sites/default/files/inlineimages/u/STM32-Pin-Details_0.png>
<http://www.handsonembedded.com/stm32f103-spl-tutorial-3/>

You might not have to get a different IR sensor.

And here's a small sketch for testing the sensor:
```
int led_pin = LED_BUILTIN;
int sensor_pin = 2; //change this to the pin where the sensor is connected
void setup() {
  pinMode(led_pin, OUTPUT);
  pinMode(sensor_pin, INPUT_PULLUP);
}
void loop() {
  digitalWrite(led_pin, !digitalRead(sensor_pin)); 
}
```
I believe it's self explanatory, if the led blinks when you press a button on the remote then it's working.

**Comment by clear-sky** [comment]
hi dear luis and thanks for your notice
changed the sensor but no success 
and then i saw your new sample code
it works!
but i cannot see any thing in serial console(HelloNEC.ino) why?

**Comment by clear-sky** [comment]
i think some code is missing like attachIntrrupt but dont know how to use it
please see : https://circuitdigest.com/microcontroller-projects/how-to-use-interrupts-in-stm32f103c8

**Comment by LuisMiCa** [comment]
I already had looked at that web page and it mentions the recommended way to attach interrupts in Arduino but, after a better look,  I noticed that, in the full code, they do something different, they use:
` attachInterrupt(PA0, buttonPressed, CHANGE); ` 
instead of the recommended
`attachInterrupt(digitalPinToInterrupt(PA0), buttonPressed, CHANGE)`

so, to test if that's the problem, you can change the line 83 in the file IRsmallDecoder.h 
from:
``` attachInterrupt(digitalPinToInterrupt(interruptPin), irISR, IR_ISR_MODE);```

to:
``` attachInterrupt(interruptPin, irISR, IR_ISR_MODE);```

**Comment by clear-sky** [comment]
happened nothing!

**Comment by LuisMiCa** [comment]
Then, without testing, myself, one of those boards , I don't know how to help you. If the attachInterrupt() function is not working, the problem might be in the core you're using.
My suggestion is to keep trying and "play around" with small examples of external interrupts like this one:
http://docs.leaflabs.com/static.leaflabs.com/pub/leaflabs/maple-docs/latest/lang/api/attachinterrupt.html#lang-attachinterrupt
and keep in mind that the problem might the fact that  interrupt 0 may not correspond to the input 0 (there are only 16 external interrupts on the Maple):
http://docs.leaflabs.com/static.leaflabs.com/pub/leaflabs/maple-docs/latest/hardware/maple.html#maple-exti-map

Good luck,
