### ISSUE TITLE
Pin Change Interrupts

### ISSUE THREAD

**Issue by betyar** [LuisMiCa/IRsmallDecoder#4]
This library looks to be exactly what I was looking for. I tried to use IRRemote but it conflicted with a SSD1306 OLED I am also using as well. I guess it must be a timer conflict. Anyway, my question is this: can I use a pin change interrupt instead of the allocated  external hardware interrupts (I am using an ATMEGA 328P)?

**Comment by LuisMiCa** [comment]
The short answer is: no, this library does not use the pin change interrupt.

However, like I mentioned in the _Possible improvements_ section, it might be possible to modify it, so it can use the NicoHood's PinChangeInterrupt Library, but I haven't got around to testing that...

If you really must use a pin that it's not on the list, try the NicoHood's IRLremote Library with the PinChangeInterrupts.

**Comment by betyar** [comment]
Thanks a lot for your quick reply and suggestion. I will try and rewire my circuit, but if it is a problem then I will try NicoHood's IRLremote Library.
